name: Docker image

on:
  push: { branches: [ develop ], tags: [ "*" ] }
  pull_request: { branches: [ develop ] }
  repository_dispatch: { types: [ "kraken-wrapper release" ] }

jobs:
  # build:
  #   runs-on: [ "self-hosted", "os:linux", "platform:${{ matrix.platform }}" ]
  #   strategy:
  #     matrix:
  #       platform: [ "arm64", "amd64" ]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - uses: docker/setup-qemu-action@v2
  #     - uses: docker/setup-buildx-action@v2
  #     - uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - uses: actions/setup-python@v2
  #       if: "${{ matrix.platform == 'amd64' }}"
  #       with:
  #         python-version: "3.9.13"

  #     - name: Create Python 3 virtualenv (arm64)
  #       if: "${{ matrix.platform == 'arm64' }}"
  #       run: python3.9 -m venv .venv

  #     - name: Activate Python 3 virtualenv (arm64)
  #       if: "${{ matrix.platform == 'arm64' }}"
  #       run: source .venv/bin/activate && env >> $GITHUB_ENV

  #     - name: Install kraken-wrapper
  #       run: pip install kraken-wrapper

  #     - run: |
  #         krakenw q d :buildDocker-linux/${{ matrix.platform }} -v
  #         krakenw r :buildDocker-linux/${{ matrix.platform }} -v
  #       env:
  #         GITHUB_USER: ${{ github.actor }}
  #         GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: kraken-build-state
  #         path: build/.kraken/build-state

  manifest-tool:
    runs-on: ubuntu-latest
    # needs: [ "build" ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: kraken-build-state

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install kraken-wrapper
        run: pip install kraken-wrapper

      - name: Install manifest-tool
        run: |
          wget https://github.com/estesp/manifest-tool/releases/download/v2.0.5/binaries-manifest-tool-2.0.5.tar.gz
          tar xvf binaries-manifest-tool-2.0.5.tar.gz manifest-tool-linux-amd64
          mv manifest-tool-linux-amd64 /usr/local/bin/manifest-tool

      - run: |
          # krakenw q d --resume :buildDocker -v
          krakenw r :buildDocker -v -X buildDocker-linux/arm64 -X buildDocker-linux/amd64  # --resume
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
